# Generated by Django 3.1.5 on 2021-12-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alertlog',
            table='alert_log',
        ),
    ]
