# Generated by Django 3.1.5 on 2021-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alertlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
